plugins {
    id "com.android.application"
}

android {
    namespace "com.example.telshevaazan"
    compileSdk 35

    defaultConfig {
        applicationId "com.example.telshevaazan"
        minSdk 23
        targetSdk 35
        versionCode 3
        versionName "0.2.1"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
