plugins {
    id "com.android.application"
}

android {
    namespace "com.example.telshevaazan"
    compileSdk 35

    defaultConfig {
        applicationId "com.example.telshevaazan"
        minSdk 23
        targetSdk 35
        versionCode 147
        versionName "0.6.56"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
